export const BITCOIN_FACTS = [
    "Bitcoin's genesis block was mined on January 3, 2009 by Satoshi Nakamoto.",
    "There will only ever be 21 million Bitcoin in existence.",
    "The first real-world Bitcoin transaction bought 2 pizzas for 10,000 BTC in 2010.",
    "Bitcoin halving occurs every 210,000 blocks, reducing the mining reward by half.",
    "Satoshi Nakamoto's true identity has never been revealed.",
    "Bitcoin operates 24/7 — it has never gone offline since its launch in 2009.",
    "Over 19.8 million Bitcoin have already been mined.",
    "The smallest unit of Bitcoin is called a Satoshi — one hundred millionth of a BTC.",
    "Bitcoin's whitepaper was published on October 31, 2008 — Halloween.",
    "The Bitcoin network has never been successfully hacked.",
    "It is estimated that around 4 million Bitcoin are lost forever due to lost private keys.",
    "Bitcoin mining uses a Proof of Work consensus mechanism.",
    "The first Bitcoin exchange rate was set in 2010 at $0.0008 per BTC.",
    "Bitcoin reached $1 for the first time in February 2011.",
    "There are over 50,000 Bitcoin nodes actively running across the globe.",
    "A new Bitcoin block is mined approximately every 10 minutes.",
    "The Bitcoin network automatically adjusts mining difficulty every 2,016 blocks.",
    "El Salvador became the first country to adopt Bitcoin as legal tender in 2021.",
    "Bitcoin's market cap has surpassed that of many of the world's largest companies.",
    "Roughly 900 new Bitcoin are mined every single day.",
    "The last Bitcoin is estimated to be mined around the year 2140.",
    "Bitcoin transactions are irreversible — once confirmed, they cannot be undone.",
    "The total value of all Bitcoin transactions ever made exceeds trillions of dollars.",
    "Bitcoin has inspired over 20,000 other cryptocurrencies since its creation.",
    "Holding Bitcoin without selling is known in the community as HODLing.",
    "A Bitcoin private key is a 256-bit number — the odds of guessing one are astronomically low.",
    "The Bitcoin symbol ₿ was approved as an official Unicode character in 2017.",
    "More than 100 million people worldwide are estimated to own Bitcoin.",
    "Bitcoin can be sent to anyone in the world in minutes, regardless of borders.",
    "The word Satoshi can refer to both Bitcoin's creator and its smallest unit.",
];

export const getRandomFact = () => {
    return BITCOIN_FACTS[Math.floor(Math.random() * BITCOIN_FACTS.length)];
};